/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QuanLi.SinhVien;
import Model.*;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author ducnam
 */
public class LichHocComponent extends javax.swing.JPanel {

    /**
     * Creates new form MonHocComponent
     */
    public LichHocComponent() {
        initComponents();
    }
    
     public LichHocComponent(Lich s) {
        initComponents();
        String tmp = String.format("%3d",s.getIdLich()).replace(' ', '0');
        this.getIdLabel().setText(s.getKhoa()+tmp);
        this.getNameLabel().setText(s.getTen());
        this.getGvLabel().setText(s.getGv().getTenGv());
        this.getRoomLabel().setText(s.getRoomNum());
        this.getTimeLabel().setText(s.getTime());
        this.getStartLabel().setText(s.getStart()+"");
        this.getDayLabel().setText(s.getDay()+"");
        this.getLichIDLabel().setText(s.getIdLich()+"");
        
    }

    public JLabel getLichIDLabel() {
        return lichIDLabel;
    }

    public void setLichIDLabel(JLabel lichIDLabel) {
        this.lichIDLabel = lichIDLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        gvLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        lichIDLabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));

        idLabel.setText("Mã Môn");

        nameLabel.setText("Tên Môn");

        timeLabel.setText("Thời gian");

        startLabel.setText("Tiết bắt đầu");

        dayLabel.setText("Ngày");

        gvLabel.setText("Giảng Viên");

        roomLabel.setText("Phòng");

        lichIDLabel.setText("Mã Lịch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addGap(18, 18, 18)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startLabel)
                .addGap(18, 18, 18)
                .addComponent(dayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lichIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(nameLabel)
                    .addComponent(dayLabel)
                    .addComponent(startLabel)
                    .addComponent(timeLabel)
                    .addComponent(gvLabel)
                    .addComponent(roomLabel)
                    .addComponent(lichIDLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getDayLabel() {
        return dayLabel;
    }

    public void setDayLabel(JLabel dayLabel) {
        this.dayLabel = dayLabel;
    }

    public JLabel getGvLabel() {
        return gvLabel;
    }

    public void setGvLabel(JLabel gvLabel) {
        this.gvLabel = gvLabel;
    }

    public JLabel getIdLabel() {
        return idLabel;
    }

    public void setIdLabel(JLabel idLabel) {
        this.idLabel = idLabel;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public void setNameLabel(JLabel nameLabel) {
        this.nameLabel = nameLabel;
    }

    public JLabel getRoomLabel() {
        return roomLabel;
    }

    public void setRoomLabel(JLabel roomLabel) {
        this.roomLabel = roomLabel;
    }

    public JLabel getStartLabel() {
        return startLabel;
    }

    public void setStartLabel(JLabel startLabel) {
        this.startLabel = startLabel;
    }

    public JLabel getTimeLabel() {
        return timeLabel;
    }

    public void setTimeLabel(JLabel timeLabel) {
        this.timeLabel = timeLabel;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayLabel;
    private javax.swing.JLabel gvLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lichIDLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
