/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QuanLi;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import java.util.ArrayList;
import Model.*;
import View.QuanLi.SinhVien.GiangVienComponent;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author LEGION
 */
public class GvDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form GvDisplayPanel
     */
    public GvDisplayPanel(ArrayList<GiangVien> gv, QuanLiFrame frame) {
        initComponents();
        setLayout(new BorderLayout());
        JScrollPane sp = new JScrollPane(createGvList(gv, frame), 
                
        JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, 
        JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        add(sp);
    }

    public JPanel createGvList(ArrayList<GiangVien> gv, QuanLiFrame frame) {
        JPanel p1 = new JPanel();
        p1.setLayout(new GridLayout(gv.size() + 1, 1, 1, 1));
        GiangVienComponent a = new GiangVienComponent();
        p1.add(a);
        ArrayList<GiangVienComponent> list = new ArrayList<>();
        for (GiangVien giang : gv) {
            GiangVienComponent tmp = new GiangVienComponent(giang);
            p1.add(tmp);
            tmp.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    frame.setGv(giang);
                    tmp.setOpaque(true);
                    tmp.setColorCustom(Color.RED);
                }

            });
        }
        
        return p1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
