/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QuanLi;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import Controller.QuanLi.*;

/**
 *
 * @author LEGION
 */
public class QuanLiFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiFrame
     */
    public QuanLiFrame() {
        initComponents();
        QLMainController ctr = new QLMainController(this);
        ctr.init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JLabel();
        mainSP = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        lectureLabel = new javax.swing.JLabel();
        studetnLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titlePanel.setText("Management");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        mainSP.setViewportView(mainTable);

        lectureLabel.setText("Lectures");

        studetnLabel.setText("Students");

        courseLabel.setText("Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainSP, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lectureLabel)
                        .addGap(39, 39, 39)
                        .addComponent(studetnLabel)
                        .addGap(34, 34, 34)
                        .addComponent(courseLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lectureLabel)
                    .addComponent(studetnLabel)
                    .addComponent(courseLabel))
                .addGap(43, 43, 43)
                .addComponent(mainSP, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiFrame().setVisible(true);
            }
        });
    }

    public JLabel getCourseLabel() {
        return courseLabel;
    }

    public void setCourseLabel(JLabel courseLabel) {
        this.courseLabel = courseLabel;
    }

    public JLabel getLectureLabel() {
        return lectureLabel;
    }

    public void setLectureLabel(JLabel lectureLabel) {
        this.lectureLabel = lectureLabel;
    }

    public JScrollPane getMainSP() {
        return mainSP;
    }

    public void setMainSP(JScrollPane mainSP) {
        this.mainSP = mainSP;
    }

    public JTable getMainTable() {
        return mainTable;
    }

    public void setMainTable(JTable mainTable) {
        this.mainTable = mainTable;
    }

    public JLabel getStudetnLabel() {
        return studetnLabel;
    }

    public void setStudetnLabel(JLabel studetnLabel) {
        this.studetnLabel = studetnLabel;
    }

    public JLabel getTitlePanel() {
        return titlePanel;
    }

    public void setTitlePanel(JLabel titlePanel) {
        this.titlePanel = titlePanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseLabel;
    private javax.swing.JLabel lectureLabel;
    private javax.swing.JScrollPane mainSP;
    private javax.swing.JTable mainTable;
    private javax.swing.JLabel studetnLabel;
    private javax.swing.JLabel titlePanel;
    // End of variables declaration//GEN-END:variables
}
