/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QuanLi;

import Model.*;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.*;
import View.QuanLi.SinhVien.*;
import java.awt.GridLayout;

/**
 *
 * @author LEGION
 */
public class SvDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form SvDisplayPanel
     */
    public SvDisplayPanel(ArrayList<SinhVien> sv) {
        initComponents();
        setLayout(new BorderLayout());
        JScrollPane sp = new JScrollPane(createSvList(sv));
        add(sp);
    }

    public JPanel createSvList(ArrayList<SinhVien> sv) {
        JPanel p1 = new JPanel();
        p1.setLayout(new GridLayout(sv.size(), 1, 0, 0));
        ArrayList<SinhVienComponent> list = new ArrayList<>();
        for (int i = 0; i < sv.size(); i++) {
            SinhVienComponent tmp = new SinhVienComponent(sv.get(i));
            p1.add(tmp);
        }
        return p1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
