/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SinhVien.Panels;

import Model.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.*;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import View.SinhVien.SVMainFrame;

/**
 *
 * @author LEGION
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPanel
     */
    public ListPanel(ArrayList<Lich> lich,SVMainFrame frame) {
        initComponents();
        JScrollPane sp = new JScrollPane(pn(lich,frame));
        add(sp);

    }

    public JPanel pn(ArrayList<Lich> lich,SVMainFrame frame) {
        JPanel p1 = new JPanel();
        p1.setLayout(new GridLayout(lich.size(), 1, 0, 0));
        for (Lich lich1 : lich) {
            LichHocComponent tmp = new LichHocComponent(lich1);
            tmp.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    frame.setLichChon(lich1);
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    tmp.setOpaque(true);
                    tmp.setBackground(Color.DARK_GRAY);
                    tmp.setForeground(Color.CYAN);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    tmp.setOpaque(false);
                    tmp.setBackground(Color.WHITE);
                    tmp.setForeground(Color.BLACK);
                }
            });
            p1.add(tmp);
        }
        return p1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/QuanLi/ImageIcon/delete.png"))); // NOI18N
        jLabel1.setText("Xóa Lịch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 245, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
