/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SinhVien.Panels;

import View.SinhVien.*;
import Controller.SinhVien.*;
import java.util.ArrayList;
import Model.*;
import java.awt.FlowLayout;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import DAO.*;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author LEGION
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    private ArrayList<GiangVien> gv = new ArrayList();
    private ArrayList<Lich> listLich = new ArrayList<>();
    public RegisterPanel(SVMainFrame frame) throws SQLException {
        initComponents();
        gv = frame.getListGV();
        ArrayList<MonHoc> mh = frame.getListMon();
        CoursePanel cp = new CoursePanel(mh,this);
        setAuxPanel(cp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        auxPanel = new javax.swing.JPanel();
        showButton = new javax.swing.JButton();

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout auxPanelLayout = new javax.swing.GroupLayout(auxPanel);
        auxPanel.setLayout(auxPanelLayout);
        auxPanelLayout.setHorizontalGroup(
            auxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        auxPanelLayout.setVerticalGroup(
            auxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        showButton.setText("DS Đăng kí");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(auxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showButton)
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(auxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(showButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getAuxPanel() {
        return auxPanel;
    }

    public ArrayList<Lich> getListLich() {
        return listLich;
    }

    public void setAuxPanel(JPanel auxPanel) {
        this.auxPanel.removeAll();
        this.auxPanel.setLayout(new FlowLayout());
        this.auxPanel.add(auxPanel);
        this.auxPanel.revalidate();
        this.auxPanel.repaint();
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel.removeAll();
        this.mainPanel.setLayout(new FlowLayout());
        this.mainPanel.add(mainPanel);
        this.mainPanel.revalidate();
        this.mainPanel.repaint();
    }

    public JButton getShowButton() {
        return showButton;
    }

    public void setShowButton(JButton showButton) {
        this.showButton = showButton;
    }
    public void saveCourse(Lich e){
        this.listLich.add(e);
    }
    
    public void createMainPanel(MonHoc a){
        System.out.println(a);
        JPanel p1 = new JPanel();
        JPanel p2 = new JPanel();
        TimetableQuery tq = new TimetableQuery();
        ArrayList<Lich> lich = new ArrayList<>();
        try {
            lich = tq.getLich(a,gv);
        } catch (Exception e) {
            e.printStackTrace();
        }
        p2.setLayout(new GridLayout(lich.size(),1,0,0));
        for (Lich lich1 : lich) {
            LichHocComponent tmp = new LichHocComponent(lich1);
            tmp.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    saveCourse(lich1);
                    System.out.println(lich1);
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    tmp.setOpaque(true);
                    tmp.setBackground(Color.DARK_GRAY);
                    tmp.setColorCustom(Color.CYAN);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    tmp.setOpaque(false);
                    tmp.setBackground(Color.WHITE);
                    tmp.setColorCustom(Color.BLACK);
                }
            });
            p2.add(tmp);
            
        }
        JScrollPane sp = new JScrollPane(p2);
        p1.add(sp);
        setMainPanel(p1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auxPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
}
